Avoid searching for Maxim board by exactly specifying the mount point
Significantly improves upload speed on unix-like machines with multiple/large volumes.
Match the code flow on Windows as closely as possible.

diff --git a/daplink/daplink b/daplink/daplink
--- a/daplink/daplink
+++ b/daplink/daplink
@@ -2,36 +2,34 @@
 
 binPath=$1
 binFile=$2
-options=$3
+mountPoint=$3
+options=$4
 
-daplinkPath=""
-searchPath=""
+mountPath=""
 
-# check OS type to decide search path and exclude metadata on darwin based OS
+# check OS type to decide the mount path
 if [[ "$OSTYPE" == "darwin"* ]]; then
-	searchPath="/Volumes"
-	options=$options" -X"
+    mountPath="/Volumes/"$mountPoint
+    options=$options" -X"   # exclude metadata on darwin based OS
 else
-	searchPath="/media"
+    mountPath="/media/$USER/"$mountPoint
 fi
 
 # print search path when verbose is enabled
 if [[ "$options" == "-v"* ]]; then echo "Searching for Maxim board in "$searchPath
 fi
 
-# find the DETAILS.TXT file, store the path. write error to null
-daplinkPath="$(find $searchPath -name DETAILS.TXT -exec dirname {} \; 2>/dev/null )"
+# Verify that Maxim board is valid before copying(loading) the binary file
+if ([ $mountPoint == "BOOTLOADER" ] && [ -e $mountPath"/DETAILS.TXT" ] && [ -e $mountPath"/HELP_FAQ.HTM" ]) \
+    || ([ $mountPoint == "DAPLINK" ] && [ -e $mountPath"/DETAILS.TXT" ] && [ -e $mountPath"/MBED.HTM" ]); then
 
-# additional check to ensure copying binary file to Maxim board
-if [ -e $daplinkPath/MBED.HTM ] || [ -e $daplinkPath/HELP_FAQ.HTM ]; then
-	cp $options $binPath/$binFile $daplinkPath
-
-	# verify if the file has been copied
-	if [ ! -e $daplinkPath/$binFile ]; then
+    cp $options $binPath/$binFile $mountPath
+	# verify if file has been copied
+	if [ ! -e $mountPath/$binFile ]; then
 		echo "Can't upload the file to USB drive."
 		exit 1
 	fi
 else
-	echo "Maxim board not found."
-	exit 1
+    echo "Maxim board not found."
+    exit 1
 fi
